stages:
  data_load:
    cmd: python src/stages/data_load.py --config=params.yaml
    deps:
    - src/stages/data_load.py
    - src/utils/data_utils.py
    params:
    - base
    - data_load
    outs:
    - data/data_ingestion/customer_booking.csv
  data_split:
    cmd: python src/stages/data_split.py --config=params.yaml
    deps:
    - src/stages/data_split.py
    - src/utils/data_utils.py
    - data/data_ingestion/customer_booking.csv
    params:
    - base
    - data_load
    - data_split
    outs:
    - data/data_transformation/train.csv
    - data/data_transformation/test.csv
  train:
    cmd: python src/stages/train.py --config=params.yaml
    deps:
    - data/data_transformation/train.csv
    - src/stages/train.py
    - src/utils/train_utils.py
    params:
    - base
    - data_split
    - train
    outs:
    - models/model.joblib
  evaluate:
    cmd: python src/stages/eval.py --config=params.yaml
    deps:
    - models/model.joblib
    - data/data_transformation/test.csv
    - src/stages/eval.py
    - src/utils/eval_utils.py
    params:
    - base
    - train
    - data_split
    - evaluate
    metrics:
    - evaluation/metrics.json
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
