name: Deploy-dev
on:
  push:
    branches:    
      - 'dev'
    tags:
      - "*#dev*"
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: cloud
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::175754385727:role/SandboxUser
      - name: Pull Model
        run: |
            pip install dvc[s3]
            dvc pull models/model.joblib
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}} # set your own via gh CLI or UI
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} # change to a different name (must be unique globally)
          heroku_email: ${{secrets.HEROKU_EMAIL}} # set your email
          usedocker: true
